---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - platform.iterabase.com
  resources:
  - identitymappings
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - platform.iterabase.com
  resources:
  - identitymappings/finalizers
  verbs:
  - update
- apiGroups:
  - platform.iterabase.com
  resources:
  - identitymappings/status
  verbs:
  - get
  - patch
  - update
