// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: iterabase/harness/v1/harness.proto

package harnessv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Settled_Reason int32

const (
	Settled_REASON_UNSPECIFIED Settled_Reason = 0
	Settled_REASON_COMPLETED   Settled_Reason = 1 // normal agent_settled
	Settled_REASON_ABORTED     Settled_Reason = 2 // Abort RPC fired
	Settled_REASON_FAILED      Settled_Reason = 3 // unrecoverable error
)

// Enum value maps for Settled_Reason.
var (
	Settled_Reason_name = map[int32]string{
		0: "REASON_UNSPECIFIED",
		1: "REASON_COMPLETED",
		2: "REASON_ABORTED",
		3: "REASON_FAILED",
	}
	Settled_Reason_value = map[string]int32{
		"REASON_UNSPECIFIED": 0,
		"REASON_COMPLETED":   1,
		"REASON_ABORTED":     2,
		"REASON_FAILED":      3,
	}
)

func (x Settled_Reason) Enum() *Settled_Reason {
	p := new(Settled_Reason)
	*p = x
	return p
}

func (x Settled_Reason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Settled_Reason) Descriptor() protoreflect.EnumDescriptor {
	return file_iterabase_harness_v1_harness_proto_enumTypes[0].Descriptor()
}

func (Settled_Reason) Type() protoreflect.EnumType {
	return &file_iterabase_harness_v1_harness_proto_enumTypes[0]
}

func (x Settled_Reason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Settled_Reason.Descriptor instead.
func (Settled_Reason) EnumDescriptor() ([]byte, []int) {
	return file_iterabase_harness_v1_harness_proto_rawDescGZIP(), []int{11, 0}
}

type PromptRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Images        []*Image               `protobuf:"bytes,2,rep,name=images,proto3" json:"images,omitempty"` // optional; the email demo is text-only
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PromptRequest) Reset() {
	*x = PromptRequest{}
	mi := &file_iterabase_harness_v1_harness_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PromptRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PromptRequest) ProtoMessage() {}

func (x *PromptRequest) ProtoReflect() protoreflect.Message {
	mi := &file_iterabase_harness_v1_harness_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PromptRequest.ProtoReflect.Descriptor instead.
func (*PromptRequest) Descriptor() ([]byte, []int) {
	return file_iterabase_harness_v1_harness_proto_rawDescGZIP(), []int{0}
}

func (x *PromptRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *PromptRequest) GetImages() []*Image {
	if x != nil {
		return x.Images
	}
	return nil
}

type Image struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	MimeType      string                 `protobuf:"bytes,2,opt,name=mime_type,json=mimeType,proto3" json:"mime_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Image) Reset() {
	*x = Image{}
	mi := &file_iterabase_harness_v1_harness_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Image) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Image) ProtoMessage() {}

func (x *Image) ProtoReflect() protoreflect.Message {
	mi := &file_iterabase_harness_v1_harness_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Image.ProtoReflect.Descriptor instead.
func (*Image) Descriptor() ([]byte, []int) {
	return file_iterabase_harness_v1_harness_proto_rawDescGZIP(), []int{1}
}

func (x *Image) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *Image) GetMimeType() string {
	if x != nil {
		return x.MimeType
	}
	return ""
}

type AbortRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AbortRequest) Reset() {
	*x = AbortRequest{}
	mi := &file_iterabase_harness_v1_harness_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AbortRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AbortRequest) ProtoMessage() {}

func (x *AbortRequest) ProtoReflect() protoreflect.Message {
	mi := &file_iterabase_harness_v1_harness_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AbortRequest.ProtoReflect.Descriptor instead.
func (*AbortRequest) Descriptor() ([]byte, []int) {
	return file_iterabase_harness_v1_harness_proto_rawDescGZIP(), []int{2}
}

type AbortResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AbortResponse) Reset() {
	*x = AbortResponse{}
	mi := &file_iterabase_harness_v1_harness_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AbortResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AbortResponse) ProtoMessage() {}

func (x *AbortResponse) ProtoReflect() protoreflect.Message {
	mi := &file_iterabase_harness_v1_harness_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AbortResponse.ProtoReflect.Descriptor instead.
func (*AbortResponse) Descriptor() ([]byte, []int) {
	return file_iterabase_harness_v1_harness_proto_rawDescGZIP(), []int{3}
}

// Event is the streamed pi event, curated to the semantic set the
// control-plane records. Deferred: message_update deltas (live token
// streaming), queue_update, compaction/retry detail.
type Event struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Kind:
	//
	//	*Event_TurnStarted
	//	*Event_AssistantMessage
	//	*Event_ToolResult
	//	*Event_Error
	//	*Event_Settled
	Kind          isEvent_Kind `protobuf_oneof:"kind"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_iterabase_harness_v1_harness_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_iterabase_harness_v1_harness_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_iterabase_harness_v1_harness_proto_rawDescGZIP(), []int{4}
}

func (x *Event) GetKind() isEvent_Kind {
	if x != nil {
		return x.Kind
	}
	return nil
}

func (x *Event) GetTurnStarted() *TurnStarted {
	if x != nil {
		if x, ok := x.Kind.(*Event_TurnStarted); ok {
			return x.TurnStarted
		}
	}
	return nil
}

func (x *Event) GetAssistantMessage() *AssistantMessage {
	if x != nil {
		if x, ok := x.Kind.(*Event_AssistantMessage); ok {
			return x.AssistantMessage
		}
	}
	return nil
}

func (x *Event) GetToolResult() *ToolResult {
	if x != nil {
		if x, ok := x.Kind.(*Event_ToolResult); ok {
			return x.ToolResult
		}
	}
	return nil
}

func (x *Event) GetError() *Error {
	if x != nil {
		if x, ok := x.Kind.(*Event_Error); ok {
			return x.Error
		}
	}
	return nil
}

func (x *Event) GetSettled() *Settled {
	if x != nil {
		if x, ok := x.Kind.(*Event_Settled); ok {
			return x.Settled
		}
	}
	return nil
}

type isEvent_Kind interface {
	isEvent_Kind()
}

type Event_TurnStarted struct {
	TurnStarted *TurnStarted `protobuf:"bytes,1,opt,name=turn_started,json=turnStarted,proto3,oneof"`
}

type Event_AssistantMessage struct {
	AssistantMessage *AssistantMessage `protobuf:"bytes,2,opt,name=assistant_message,json=assistantMessage,proto3,oneof"`
}

type Event_ToolResult struct {
	ToolResult *ToolResult `protobuf:"bytes,3,opt,name=tool_result,json=toolResult,proto3,oneof"`
}

type Event_Error struct {
	Error *Error `protobuf:"bytes,4,opt,name=error,proto3,oneof"`
}

type Event_Settled struct {
	Settled *Settled `protobuf:"bytes,5,opt,name=settled,proto3,oneof"` // terminal; the stream closes after this
}

func (*Event_TurnStarted) isEvent_Kind() {}

func (*Event_AssistantMessage) isEvent_Kind() {}

func (*Event_ToolResult) isEvent_Kind() {}

func (*Event_Error) isEvent_Kind() {}

func (*Event_Settled) isEvent_Kind() {}

type TurnStarted struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Model         string                 `protobuf:"bytes,1,opt,name=model,proto3" json:"model,omitempty"`                                      // provider/modelId in use
	ThinkingLevel string                 `protobuf:"bytes,2,opt,name=thinking_level,json=thinkingLevel,proto3" json:"thinking_level,omitempty"` // off|low|medium|high|...
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TurnStarted) Reset() {
	*x = TurnStarted{}
	mi := &file_iterabase_harness_v1_harness_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TurnStarted) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TurnStarted) ProtoMessage() {}

func (x *TurnStarted) ProtoReflect() protoreflect.Message {
	mi := &file_iterabase_harness_v1_harness_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TurnStarted.ProtoReflect.Descriptor instead.
func (*TurnStarted) Descriptor() ([]byte, []int) {
	return file_iterabase_harness_v1_harness_proto_rawDescGZIP(), []int{5}
}

func (x *TurnStarted) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *TurnStarted) GetThinkingLevel() string {
	if x != nil {
		return x.ThinkingLevel
	}
	return ""
}

// AssistantMessage carries the turn's assistant output: text + tool calls +
// usage. Emitted at pi message_end (role=assistant).
type AssistantMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	ToolCalls     []*ToolCall            `protobuf:"bytes,2,rep,name=tool_calls,json=toolCalls,proto3" json:"tool_calls,omitempty"`
	Usage         *Usage                 `protobuf:"bytes,3,opt,name=usage,proto3" json:"usage,omitempty"`
	StopReason    string                 `protobuf:"bytes,4,opt,name=stop_reason,json=stopReason,proto3" json:"stop_reason,omitempty"` // stop|length|toolUse|error|aborted
	TimestampMs   int64                  `protobuf:"varint,5,opt,name=timestamp_ms,json=timestampMs,proto3" json:"timestamp_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssistantMessage) Reset() {
	*x = AssistantMessage{}
	mi := &file_iterabase_harness_v1_harness_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssistantMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssistantMessage) ProtoMessage() {}

func (x *AssistantMessage) ProtoReflect() protoreflect.Message {
	mi := &file_iterabase_harness_v1_harness_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssistantMessage.ProtoReflect.Descriptor instead.
func (*AssistantMessage) Descriptor() ([]byte, []int) {
	return file_iterabase_harness_v1_harness_proto_rawDescGZIP(), []int{6}
}

func (x *AssistantMessage) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *AssistantMessage) GetToolCalls() []*ToolCall {
	if x != nil {
		return x.ToolCalls
	}
	return nil
}

func (x *AssistantMessage) GetUsage() *Usage {
	if x != nil {
		return x.Usage
	}
	return nil
}

func (x *AssistantMessage) GetStopReason() string {
	if x != nil {
		return x.StopReason
	}
	return ""
}

func (x *AssistantMessage) GetTimestampMs() int64 {
	if x != nil {
		return x.TimestampMs
	}
	return 0
}

type ToolCall struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	ArgumentsJson string                 `protobuf:"bytes,3,opt,name=arguments_json,json=argumentsJson,proto3" json:"arguments_json,omitempty"` // the LLM's raw tool-call args (JSON string)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToolCall) Reset() {
	*x = ToolCall{}
	mi := &file_iterabase_harness_v1_harness_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolCall) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolCall) ProtoMessage() {}

func (x *ToolCall) ProtoReflect() protoreflect.Message {
	mi := &file_iterabase_harness_v1_harness_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolCall.ProtoReflect.Descriptor instead.
func (*ToolCall) Descriptor() ([]byte, []int) {
	return file_iterabase_harness_v1_harness_proto_rawDescGZIP(), []int{7}
}

func (x *ToolCall) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ToolCall) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ToolCall) GetArgumentsJson() string {
	if x != nil {
		return x.ArgumentsJson
	}
	return ""
}

// ToolResult is the granular per-call audit record (pi tool_execution_end).
type ToolResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ToolCallId    string                 `protobuf:"bytes,1,opt,name=tool_call_id,json=toolCallId,proto3" json:"tool_call_id,omitempty"`
	ToolName      string                 `protobuf:"bytes,2,opt,name=tool_name,json=toolName,proto3" json:"tool_name,omitempty"`
	ArgumentsJson string                 `protobuf:"bytes,3,opt,name=arguments_json,json=argumentsJson,proto3" json:"arguments_json,omitempty"`
	ResultText    string                 `protobuf:"bytes,4,opt,name=result_text,json=resultText,proto3" json:"result_text,omitempty"` // result content (text); large blobs offloaded by control-plane
	IsError       bool                   `protobuf:"varint,5,opt,name=is_error,json=isError,proto3" json:"is_error,omitempty"`
	TimestampMs   int64                  `protobuf:"varint,6,opt,name=timestamp_ms,json=timestampMs,proto3" json:"timestamp_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToolResult) Reset() {
	*x = ToolResult{}
	mi := &file_iterabase_harness_v1_harness_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolResult) ProtoMessage() {}

func (x *ToolResult) ProtoReflect() protoreflect.Message {
	mi := &file_iterabase_harness_v1_harness_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolResult.ProtoReflect.Descriptor instead.
func (*ToolResult) Descriptor() ([]byte, []int) {
	return file_iterabase_harness_v1_harness_proto_rawDescGZIP(), []int{8}
}

func (x *ToolResult) GetToolCallId() string {
	if x != nil {
		return x.ToolCallId
	}
	return ""
}

func (x *ToolResult) GetToolName() string {
	if x != nil {
		return x.ToolName
	}
	return ""
}

func (x *ToolResult) GetArgumentsJson() string {
	if x != nil {
		return x.ArgumentsJson
	}
	return ""
}

func (x *ToolResult) GetResultText() string {
	if x != nil {
		return x.ResultText
	}
	return ""
}

func (x *ToolResult) GetIsError() bool {
	if x != nil {
		return x.IsError
	}
	return false
}

func (x *ToolResult) GetTimestampMs() int64 {
	if x != nil {
		return x.TimestampMs
	}
	return 0
}

type Usage struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	InputTokens      int64                  `protobuf:"varint,1,opt,name=input_tokens,json=inputTokens,proto3" json:"input_tokens,omitempty"`
	OutputTokens     int64                  `protobuf:"varint,2,opt,name=output_tokens,json=outputTokens,proto3" json:"output_tokens,omitempty"`
	CacheReadTokens  int64                  `protobuf:"varint,3,opt,name=cache_read_tokens,json=cacheReadTokens,proto3" json:"cache_read_tokens,omitempty"`
	CacheWriteTokens int64                  `protobuf:"varint,4,opt,name=cache_write_tokens,json=cacheWriteTokens,proto3" json:"cache_write_tokens,omitempty"`
	CostUsd          float64                `protobuf:"fixed64,5,opt,name=cost_usd,json=costUsd,proto3" json:"cost_usd,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Usage) Reset() {
	*x = Usage{}
	mi := &file_iterabase_harness_v1_harness_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Usage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Usage) ProtoMessage() {}

func (x *Usage) ProtoReflect() protoreflect.Message {
	mi := &file_iterabase_harness_v1_harness_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Usage.ProtoReflect.Descriptor instead.
func (*Usage) Descriptor() ([]byte, []int) {
	return file_iterabase_harness_v1_harness_proto_rawDescGZIP(), []int{9}
}

func (x *Usage) GetInputTokens() int64 {
	if x != nil {
		return x.InputTokens
	}
	return 0
}

func (x *Usage) GetOutputTokens() int64 {
	if x != nil {
		return x.OutputTokens
	}
	return 0
}

func (x *Usage) GetCacheReadTokens() int64 {
	if x != nil {
		return x.CacheReadTokens
	}
	return 0
}

func (x *Usage) GetCacheWriteTokens() int64 {
	if x != nil {
		return x.CacheWriteTokens
	}
	return 0
}

func (x *Usage) GetCostUsd() float64 {
	if x != nil {
		return x.CostUsd
	}
	return 0
}

// Error is non-terminal: a tool/extension/retry error mid-turn that the turn
// may recover from. Terminal failures surface as Settled{failed}.
type Error struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Source        string                 `protobuf:"bytes,1,opt,name=source,proto3" json:"source,omitempty"` // extension|retry|internal|tool
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Error) Reset() {
	*x = Error{}
	mi := &file_iterabase_harness_v1_harness_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Error) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Error) ProtoMessage() {}

func (x *Error) ProtoReflect() protoreflect.Message {
	mi := &file_iterabase_harness_v1_harness_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Error.ProtoReflect.Descriptor instead.
func (*Error) Descriptor() ([]byte, []int) {
	return file_iterabase_harness_v1_harness_proto_rawDescGZIP(), []int{10}
}

func (x *Error) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *Error) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// Settled is the terminal event; the stream closes after it.
type Settled struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reason        Settled_Reason         `protobuf:"varint,1,opt,name=reason,proto3,enum=iterabase.harness.v1.Settled_Reason" json:"reason,omitempty"`
	MessageCount  int32                  `protobuf:"varint,2,opt,name=message_count,json=messageCount,proto3" json:"message_count,omitempty"` // session message count after the turn
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Settled) Reset() {
	*x = Settled{}
	mi := &file_iterabase_harness_v1_harness_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Settled) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Settled) ProtoMessage() {}

func (x *Settled) ProtoReflect() protoreflect.Message {
	mi := &file_iterabase_harness_v1_harness_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Settled.ProtoReflect.Descriptor instead.
func (*Settled) Descriptor() ([]byte, []int) {
	return file_iterabase_harness_v1_harness_proto_rawDescGZIP(), []int{11}
}

func (x *Settled) GetReason() Settled_Reason {
	if x != nil {
		return x.Reason
	}
	return Settled_REASON_UNSPECIFIED
}

func (x *Settled) GetMessageCount() int32 {
	if x != nil {
		return x.MessageCount
	}
	return 0
}

var File_iterabase_harness_v1_harness_proto protoreflect.FileDescriptor

const file_iterabase_harness_v1_harness_proto_rawDesc = "" +
	"\n" +
	"\"iterabase/harness/v1/harness.proto\x12\x14iterabase.harness.v1\"^\n" +
	"\rPromptRequest\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x123\n" +
	"\x06images\x18\x02 \x03(\v2\x1b.iterabase.harness.v1.ImageR\x06images\"8\n" +
	"\x05Image\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\x12\x1b\n" +
	"\tmime_type\x18\x02 \x01(\tR\bmimeType\"\x0e\n" +
	"\fAbortRequest\"\x0f\n" +
	"\rAbortResponse\"\xe3\x02\n" +
	"\x05Event\x12F\n" +
	"\fturn_started\x18\x01 \x01(\v2!.iterabase.harness.v1.TurnStartedH\x00R\vturnStarted\x12U\n" +
	"\x11assistant_message\x18\x02 \x01(\v2&.iterabase.harness.v1.AssistantMessageH\x00R\x10assistantMessage\x12C\n" +
	"\vtool_result\x18\x03 \x01(\v2 .iterabase.harness.v1.ToolResultH\x00R\n" +
	"toolResult\x123\n" +
	"\x05error\x18\x04 \x01(\v2\x1b.iterabase.harness.v1.ErrorH\x00R\x05error\x129\n" +
	"\asettled\x18\x05 \x01(\v2\x1d.iterabase.harness.v1.SettledH\x00R\asettledB\x06\n" +
	"\x04kind\"J\n" +
	"\vTurnStarted\x12\x14\n" +
	"\x05model\x18\x01 \x01(\tR\x05model\x12%\n" +
	"\x0ethinking_level\x18\x02 \x01(\tR\rthinkingLevel\"\xdc\x01\n" +
	"\x10AssistantMessage\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\x12=\n" +
	"\n" +
	"tool_calls\x18\x02 \x03(\v2\x1e.iterabase.harness.v1.ToolCallR\ttoolCalls\x121\n" +
	"\x05usage\x18\x03 \x01(\v2\x1b.iterabase.harness.v1.UsageR\x05usage\x12\x1f\n" +
	"\vstop_reason\x18\x04 \x01(\tR\n" +
	"stopReason\x12!\n" +
	"\ftimestamp_ms\x18\x05 \x01(\x03R\vtimestampMs\"U\n" +
	"\bToolCall\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12%\n" +
	"\x0earguments_json\x18\x03 \x01(\tR\rargumentsJson\"\xd1\x01\n" +
	"\n" +
	"ToolResult\x12 \n" +
	"\ftool_call_id\x18\x01 \x01(\tR\n" +
	"toolCallId\x12\x1b\n" +
	"\ttool_name\x18\x02 \x01(\tR\btoolName\x12%\n" +
	"\x0earguments_json\x18\x03 \x01(\tR\rargumentsJson\x12\x1f\n" +
	"\vresult_text\x18\x04 \x01(\tR\n" +
	"resultText\x12\x19\n" +
	"\bis_error\x18\x05 \x01(\bR\aisError\x12!\n" +
	"\ftimestamp_ms\x18\x06 \x01(\x03R\vtimestampMs\"\xc4\x01\n" +
	"\x05Usage\x12!\n" +
	"\finput_tokens\x18\x01 \x01(\x03R\vinputTokens\x12#\n" +
	"\routput_tokens\x18\x02 \x01(\x03R\foutputTokens\x12*\n" +
	"\x11cache_read_tokens\x18\x03 \x01(\x03R\x0fcacheReadTokens\x12,\n" +
	"\x12cache_write_tokens\x18\x04 \x01(\x03R\x10cacheWriteTokens\x12\x19\n" +
	"\bcost_usd\x18\x05 \x01(\x01R\acostUsd\"9\n" +
	"\x05Error\x12\x16\n" +
	"\x06source\x18\x01 \x01(\tR\x06source\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\xcb\x01\n" +
	"\aSettled\x12<\n" +
	"\x06reason\x18\x01 \x01(\x0e2$.iterabase.harness.v1.Settled.ReasonR\x06reason\x12#\n" +
	"\rmessage_count\x18\x02 \x01(\x05R\fmessageCount\"]\n" +
	"\x06Reason\x12\x16\n" +
	"\x12REASON_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10REASON_COMPLETED\x10\x01\x12\x12\n" +
	"\x0eREASON_ABORTED\x10\x02\x12\x11\n" +
	"\rREASON_FAILED\x10\x032\xa9\x01\n" +
	"\aHarness\x12L\n" +
	"\x06Prompt\x12#.iterabase.harness.v1.PromptRequest\x1a\x1b.iterabase.harness.v1.Event0\x01\x12P\n" +
	"\x05Abort\x12\".iterabase.harness.v1.AbortRequest\x1a#.iterabase.harness.v1.AbortResponseB\xf6\x01\n" +
	"\x18com.iterabase.harness.v1B\fHarnessProtoP\x01ZZgithub.com/nunocgoncalves/control-plane/internal/harnessrpc/iterabase/harness/v1;harnessv1\xa2\x02\x03IHX\xaa\x02\x14Iterabase.Harness.V1\xca\x02\x14Iterabase\\Harness\\V1\xe2\x02 Iterabase\\Harness\\V1\\GPBMetadata\xea\x02\x16Iterabase::Harness::V1b\x06proto3"

var (
	file_iterabase_harness_v1_harness_proto_rawDescOnce sync.Once
	file_iterabase_harness_v1_harness_proto_rawDescData []byte
)

func file_iterabase_harness_v1_harness_proto_rawDescGZIP() []byte {
	file_iterabase_harness_v1_harness_proto_rawDescOnce.Do(func() {
		file_iterabase_harness_v1_harness_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_iterabase_harness_v1_harness_proto_rawDesc), len(file_iterabase_harness_v1_harness_proto_rawDesc)))
	})
	return file_iterabase_harness_v1_harness_proto_rawDescData
}

var file_iterabase_harness_v1_harness_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_iterabase_harness_v1_harness_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_iterabase_harness_v1_harness_proto_goTypes = []any{
	(Settled_Reason)(0),      // 0: iterabase.harness.v1.Settled.Reason
	(*PromptRequest)(nil),    // 1: iterabase.harness.v1.PromptRequest
	(*Image)(nil),            // 2: iterabase.harness.v1.Image
	(*AbortRequest)(nil),     // 3: iterabase.harness.v1.AbortRequest
	(*AbortResponse)(nil),    // 4: iterabase.harness.v1.AbortResponse
	(*Event)(nil),            // 5: iterabase.harness.v1.Event
	(*TurnStarted)(nil),      // 6: iterabase.harness.v1.TurnStarted
	(*AssistantMessage)(nil), // 7: iterabase.harness.v1.AssistantMessage
	(*ToolCall)(nil),         // 8: iterabase.harness.v1.ToolCall
	(*ToolResult)(nil),       // 9: iterabase.harness.v1.ToolResult
	(*Usage)(nil),            // 10: iterabase.harness.v1.Usage
	(*Error)(nil),            // 11: iterabase.harness.v1.Error
	(*Settled)(nil),          // 12: iterabase.harness.v1.Settled
}
var file_iterabase_harness_v1_harness_proto_depIdxs = []int32{
	2,  // 0: iterabase.harness.v1.PromptRequest.images:type_name -> iterabase.harness.v1.Image
	6,  // 1: iterabase.harness.v1.Event.turn_started:type_name -> iterabase.harness.v1.TurnStarted
	7,  // 2: iterabase.harness.v1.Event.assistant_message:type_name -> iterabase.harness.v1.AssistantMessage
	9,  // 3: iterabase.harness.v1.Event.tool_result:type_name -> iterabase.harness.v1.ToolResult
	11, // 4: iterabase.harness.v1.Event.error:type_name -> iterabase.harness.v1.Error
	12, // 5: iterabase.harness.v1.Event.settled:type_name -> iterabase.harness.v1.Settled
	8,  // 6: iterabase.harness.v1.AssistantMessage.tool_calls:type_name -> iterabase.harness.v1.ToolCall
	10, // 7: iterabase.harness.v1.AssistantMessage.usage:type_name -> iterabase.harness.v1.Usage
	0,  // 8: iterabase.harness.v1.Settled.reason:type_name -> iterabase.harness.v1.Settled.Reason
	1,  // 9: iterabase.harness.v1.Harness.Prompt:input_type -> iterabase.harness.v1.PromptRequest
	3,  // 10: iterabase.harness.v1.Harness.Abort:input_type -> iterabase.harness.v1.AbortRequest
	5,  // 11: iterabase.harness.v1.Harness.Prompt:output_type -> iterabase.harness.v1.Event
	4,  // 12: iterabase.harness.v1.Harness.Abort:output_type -> iterabase.harness.v1.AbortResponse
	11, // [11:13] is the sub-list for method output_type
	9,  // [9:11] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_iterabase_harness_v1_harness_proto_init() }
func file_iterabase_harness_v1_harness_proto_init() {
	if File_iterabase_harness_v1_harness_proto != nil {
		return
	}
	file_iterabase_harness_v1_harness_proto_msgTypes[4].OneofWrappers = []any{
		(*Event_TurnStarted)(nil),
		(*Event_AssistantMessage)(nil),
		(*Event_ToolResult)(nil),
		(*Event_Error)(nil),
		(*Event_Settled)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_iterabase_harness_v1_harness_proto_rawDesc), len(file_iterabase_harness_v1_harness_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_iterabase_harness_v1_harness_proto_goTypes,
		DependencyIndexes: file_iterabase_harness_v1_harness_proto_depIdxs,
		EnumInfos:         file_iterabase_harness_v1_harness_proto_enumTypes,
		MessageInfos:      file_iterabase_harness_v1_harness_proto_msgTypes,
	}.Build()
	File_iterabase_harness_v1_harness_proto = out.File
	file_iterabase_harness_v1_harness_proto_goTypes = nil
	file_iterabase_harness_v1_harness_proto_depIdxs = nil
}
