// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: iterabase/harness/v1/harness.proto

package harnessv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/nunocgoncalves/control-plane/internal/harnessrpc/iterabase/harness/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// HarnessName is the fully-qualified name of the Harness service.
	HarnessName = "iterabase.harness.v1.Harness"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// HarnessPromptProcedure is the fully-qualified name of the Harness's Prompt RPC.
	HarnessPromptProcedure = "/iterabase.harness.v1.Harness/Prompt"
	// HarnessAbortProcedure is the fully-qualified name of the Harness's Abort RPC.
	HarnessAbortProcedure = "/iterabase.harness.v1.Harness/Abort"
)

// HarnessClient is a client for the iterabase.harness.v1.Harness service.
type HarnessClient interface {
	// Prompt sends a user message and streams curated agent events until the
	// turn settles, then the stream closes. The control-plane records events to
	// the Postgres event/audit log (HOR-249). Per-task instructions ride in
	// `message`; the persona/system prompt is pod-level config.
	Prompt(context.Context, *connect.Request[v1.PromptRequest]) (*connect.ServerStreamForClient[v1.Event], error)
	// Abort cancels the pod's active turn (one pod = one active turn). The
	// in-flight Prompt stream then emits Settled{aborted} and closes.
	Abort(context.Context, *connect.Request[v1.AbortRequest]) (*connect.Response[v1.AbortResponse], error)
}

// NewHarnessClient constructs a client for the iterabase.harness.v1.Harness service. By default, it
// uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewHarnessClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) HarnessClient {
	baseURL = strings.TrimRight(baseURL, "/")
	harnessMethods := v1.File_iterabase_harness_v1_harness_proto.Services().ByName("Harness").Methods()
	return &harnessClient{
		prompt: connect.NewClient[v1.PromptRequest, v1.Event](
			httpClient,
			baseURL+HarnessPromptProcedure,
			connect.WithSchema(harnessMethods.ByName("Prompt")),
			connect.WithClientOptions(opts...),
		),
		abort: connect.NewClient[v1.AbortRequest, v1.AbortResponse](
			httpClient,
			baseURL+HarnessAbortProcedure,
			connect.WithSchema(harnessMethods.ByName("Abort")),
			connect.WithClientOptions(opts...),
		),
	}
}

// harnessClient implements HarnessClient.
type harnessClient struct {
	prompt *connect.Client[v1.PromptRequest, v1.Event]
	abort  *connect.Client[v1.AbortRequest, v1.AbortResponse]
}

// Prompt calls iterabase.harness.v1.Harness.Prompt.
func (c *harnessClient) Prompt(ctx context.Context, req *connect.Request[v1.PromptRequest]) (*connect.ServerStreamForClient[v1.Event], error) {
	return c.prompt.CallServerStream(ctx, req)
}

// Abort calls iterabase.harness.v1.Harness.Abort.
func (c *harnessClient) Abort(ctx context.Context, req *connect.Request[v1.AbortRequest]) (*connect.Response[v1.AbortResponse], error) {
	return c.abort.CallUnary(ctx, req)
}

// HarnessHandler is an implementation of the iterabase.harness.v1.Harness service.
type HarnessHandler interface {
	// Prompt sends a user message and streams curated agent events until the
	// turn settles, then the stream closes. The control-plane records events to
	// the Postgres event/audit log (HOR-249). Per-task instructions ride in
	// `message`; the persona/system prompt is pod-level config.
	Prompt(context.Context, *connect.Request[v1.PromptRequest], *connect.ServerStream[v1.Event]) error
	// Abort cancels the pod's active turn (one pod = one active turn). The
	// in-flight Prompt stream then emits Settled{aborted} and closes.
	Abort(context.Context, *connect.Request[v1.AbortRequest]) (*connect.Response[v1.AbortResponse], error)
}

// NewHarnessHandler builds an HTTP handler from the service implementation. It returns the path on
// which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewHarnessHandler(svc HarnessHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	harnessMethods := v1.File_iterabase_harness_v1_harness_proto.Services().ByName("Harness").Methods()
	harnessPromptHandler := connect.NewServerStreamHandler(
		HarnessPromptProcedure,
		svc.Prompt,
		connect.WithSchema(harnessMethods.ByName("Prompt")),
		connect.WithHandlerOptions(opts...),
	)
	harnessAbortHandler := connect.NewUnaryHandler(
		HarnessAbortProcedure,
		svc.Abort,
		connect.WithSchema(harnessMethods.ByName("Abort")),
		connect.WithHandlerOptions(opts...),
	)
	return "/iterabase.harness.v1.Harness/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case HarnessPromptProcedure:
			harnessPromptHandler.ServeHTTP(w, r)
		case HarnessAbortProcedure:
			harnessAbortHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedHarnessHandler returns CodeUnimplemented from all methods.
type UnimplementedHarnessHandler struct{}

func (UnimplementedHarnessHandler) Prompt(context.Context, *connect.Request[v1.PromptRequest], *connect.ServerStream[v1.Event]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("iterabase.harness.v1.Harness.Prompt is not implemented"))
}

func (UnimplementedHarnessHandler) Abort(context.Context, *connect.Request[v1.AbortRequest]) (*connect.Response[v1.AbortResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("iterabase.harness.v1.Harness.Abort is not implemented"))
}
